Module5 task1
htmlacademy-react/1424545-what-to-watch-6 pull request #8
Opened 2021-02-24 18:21 UTC by libertasia

2021-02-25 21:27 UTC, DmitryMarkov requested changes
По таймауту пришлю попозже свои мысли, тут и так есть что исправить :)

2021-02-26 12:41 UTC, libertasia commented on src/film-utils.js
> +  genres.sort();
Да, но в markup жанры были указаны в алфавитном порядке, поэтому я их и сортирую.

2021-02-26 12:49 UTC, libertasia commented on src/film-utils.js
> +  return films.filter((f) => f.genre === genre);
Не поняла, какие сокращения, ветка else ?

2021-02-26 12:50 UTC, libertasia commented on src/film-utils.js
> +  });
6)  **Список жанров строится на основании изначального списка фильмов. В списке жанров перечислены уникальные жанры, то есть не может быть двух вариантов Comedy, например. Первым в списке жанров всегда располагается All genres.** 

Вытаскиваю жанры из массива объектов с фильмами, затем сортирую в алфавитном порядке, избавляюсь от повторов и добавляю в начало All genres.

2021-02-26 12:51 UTC, libertasia commented on src/index.js
> +        films={films}
Это временно, потому что еще не все компоненты работают со стором. Иначе невозможно тестировать локально.

2021-02-26 12:53 UTC, libertasia commented on src/store/reducer.js
> +        ...initialState
ок

2021-02-26 12:53 UTC, libertasia commented on src/components/pages/main/genres-list.jsx
> +      {genres.map((item, index) =>
хорошо)

2021-02-26 12:55 UTC, libertasia commented on src/shapes.jsx
> +const onGenreClickShape = PropTypes.func.isRequired;
хорошо)

2021-02-26 12:55 UTC, libertasia commented on src/shapes.jsx
> +const GenreShape = PropTypes.string.isRequired;
хорошо

2021-02-26 13:56 UTC, DmitryMarkov commented on src/film-utils.js
> +  return films.filter((f) => f.genre === genre);
названия переменных, критерий Б6

https://up.htmlacademy.ru/react/6/criteries#b6

2021-02-26 13:57 UTC, DmitryMarkov commented on src/film-utils.js
> +  });
Но можно перебирать массив из аргументов, зачем конкретно этот цикл?

2021-02-26 15:56 UTC, DmitryMarkov approved these changes
Отлично!

2021-02-26 15:56 UTC, merged